import { useEffect, useMemo, useState } from "react";
import { createFileRoute, notFound } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, ChevronDown, ChevronLeft, ChevronRight, Download, Search, TriangleAlert } from "lucide-react";
import { AppLink as Link } from "@/lib/app-link";
import { DashboardNav } from "@/components/dashboard/DashboardNav";
import { ThemeToggle } from "@/components/ThemeToggle";
import { OpportunityGapChart } from "@/components/dashboard/OpportunityGapChart";
import { Button } from "@/components/ui/button";
import { REPORT_ACTIONS, REPORT_FINDINGS, REPORT_PAGES, type Figure, type Finding, type InvestigatePage } from "@/lib/opportunity-report";
import { UNMAPPED_CLICK_SHARE, gapOf, getOpportunity, money, pct, type PageTypeOpportunity } from "@/lib/opportunity-data";

type Variant = "loading" | "empty" | "stale" | "no-crawl" | "not-reached" | "rules-changed" | "unmapped" | "directional" | "no-findings" | "missing-assessment";
const variants: Variant[] = ["loading", "empty", "stale", "no-crawl", "not-reached", "rules-changed", "unmapped", "directional", "no-findings", "missing-assessment"];
export const Route = createFileRoute("/project/$projectId/dashboard/opportunity/$pageType")({
  component: OpportunityBreakdownPage,
  validateSearch: (search: Record<string, unknown>): { state?: Variant } => ({ state: variants.includes(search.state as Variant) ? search.state as Variant : undefined }),
  loader: ({ params }) => {
    const opportunity = getOpportunity(params.pageType);
    if (!opportunity) throw notFound();
    return { slug: opportunity.slug, name: opportunity.name };
  },
  head: ({ loaderData }) => {
    const title = `${loaderData?.name ?? "Opportunity breakdown"} — OrganicOS`;
    const description = `Measured findings, prioritised fixes and affected URLs for ${loaderData?.name?.toLowerCase() ?? "one page type"}.`;
    return { meta: [{ title }, { name: "description", content: description }, { property: "og:title", content: title }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] };
  },
});

function Evidence({ figure, assumed = false, directional = false, stale = false }: { figure: Figure; assumed?: boolean; directional?: boolean; stale?: boolean }) {
  const display = figure.kind === "Observed" || figure.kind === "No estimate" ? figure.text : `${money(0).charAt(0)}${figure.text}`;
  const styles = { Observed: "border-chart-4/40 bg-chart-4/10 text-chart-4", Estimated: "border-primary/40 bg-primary/10 text-primary", "On affected pages": "border-chart-3/40 bg-chart-3/10 text-chart-3", "No estimate": "border-border bg-surface text-muted-foreground" };
  return <span className="inline-flex min-w-0 flex-wrap items-center gap-1.5 text-xs" title={figure.assumption}>
    <span className="font-mono font-semibold text-foreground">{display}</span>
    {figure.kind !== "No estimate" && <span className={`rounded-sm border px-1.5 py-0.5 font-mono text-[10px] ${styles[figure.kind]}`}>{figure.kind === "Estimated" ? "Estimated · modelled opportunity" : figure.kind}</span>}
    {assumed && figure.kind !== "Observed" && figure.kind !== "No estimate" && <Modifier name="Assumed" />}
    {directional && <Modifier name="Directional" />}
    {stale && <Modifier name="Stale · 15 Sep" />}
    {figure.assumption && <span className="basis-full text-[11px] text-muted-foreground">{figure.assumption}</span>}
  </span>;
}
function Modifier({ name }: { name: string }) { return <span className="rounded-sm border border-chart-4/40 px-1.5 py-0.5 font-mono text-[10px] text-chart-4">{name}</span>; }
function SectionHeading({ number, title, note }: { number: string; title: string; note?: string }) { return <div className="mb-5 border-b border-border pb-4"><p className="font-mono text-[10px] uppercase tracking-wider text-primary">{number} / Opportunity breakdown</p><h2 className="mt-1 text-xl font-semibold">{title}</h2>{note && <p className="mt-1 text-xs text-muted-foreground">{note}</p>}</div>; }
function OpportunityBreakdownPage() {
  const { slug } = Route.useLoaderData();
  const { state } = Route.useSearch();
  const opportunity = getOpportunity(slug);
  if (!opportunity) return null;
  const demo = slug === "routes";
  const assumed = demo || opportunity.estimated;
  const directional = state === "directional" || opportunity.confidence === "Directional";
  return <div className="min-h-screen bg-background text-foreground"><DashboardNav /><div className="min-w-0 lg:pl-56">
    <header className="sticky top-0 z-20 border-b border-border bg-background/95 px-5 py-4 backdrop-blur lg:px-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><Link to="/dashboard" className="inline-flex items-center gap-1.5 font-mono text-[10px] uppercase text-muted-foreground hover:text-primary"><ArrowLeft className="size-3" /> Back to Revenue &amp; Opportunities</Link><h1 className="mt-1 text-2xl font-semibold">{opportunity.name}</h1></div><div className="flex flex-wrap items-center gap-2 font-mono text-[11px] text-muted-foreground"><span>Search 25 Aug–21 Sep 2026</span><span className="hidden sm:inline">·</span><span>{state === "no-crawl" ? "No crawl yet" : "Crawl 15 Sep 2026"}</span><ThemeToggle /></div></div></header>
    <main className="mx-auto max-w-[1440px] space-y-10 px-5 py-7 lg:px-8 lg:py-9">
      {state === "loading" ? <Loading /> : state === "empty" ? <Empty name={opportunity.name} /> : <>
        {(state === "unmapped" || UNMAPPED_CLICK_SHARE >= 0.4) && <div className="flex gap-2 border-l-2 border-chart-4 bg-chart-4/10 p-3 text-sm text-foreground"><TriangleAlert className="size-4 shrink-0 text-chart-4" /><span>40% of clicks aren't assigned to a page type. Figures may be understated. <Link to="/settings" className="text-primary underline">Review page-type rules</Link>.</span></div>}
        <RevenuePosition opportunity={opportunity} assumed={assumed} directional={directional} demo={demo} />
        <Diagnosis demo={demo} state={state} assumed={assumed} directional={directional} noGap={gapOf(opportunity) === 0} />
        <Actions demo={demo} state={state} assumed={assumed} directional={directional} opportunity={opportunity} />
        <Pages demo={demo} state={state} assumed={assumed} directional={directional} opportunity={opportunity} />
        <Limits opportunity={opportunity} demo={demo} state={state} assumed={assumed} />
      </>}
    </main>
  </div></div>;
}
function RevenuePosition({ opportunity, assumed, directional, demo }: { opportunity: PageTypeOpportunity; assumed: boolean; directional: boolean; demo: boolean }) {
  const gap = gapOf(opportunity);
  return <section id="revenue-position"><SectionHeading number="01" title="Revenue position" note="Where this page type stands against its modelled ceiling" />
    {gap === 0 && <p className="mb-4 border-l-2 border-primary pl-3 text-sm text-primary">At or above modelled ceiling. Findings below are about protecting existing revenue.</p>}
    <div className="grid gap-px border-y border-border bg-border md:grid-cols-3"><RevenueMetric title="Current annual revenue" value={money(opportunity.current, { suffix: "/yr" })} label={assumed ? "Assumed" : "Observed"} detail={assumed ? "Configured conversion rate; no analytics connected" : "Measured revenue"} /><RevenueMetric title="Potential · modelled ceiling" value={money(opportunity.potential, { suffix: "/yr" })} label="Estimated · modelled opportunity" detail="Scenario ceiling, not a forecast" /><RevenueMetric title="Gap · modelled ceiling difference" value={money(gap, { suffix: "/yr" })} label="Estimated · modelled opportunity" detail="Not attributed to findings or actions" /></div>
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-b border-border pb-5 text-sm"><p><span className="font-medium">What changed</span> <span className="mx-2 text-muted-foreground">/</span> {demo ? "41,200 clicks in week of 15 Sep" : "Weekly click comparison not available"} <span className="mx-2 text-muted-foreground">·</span> <Evidence figure={{ kind: demo ? "Observed" : "No estimate", text: demo ? "Down 3,100 clicks vs week of 8 Sep" : "No estimate" }} /></p><span className="font-mono text-xs text-muted-foreground">{directional ? "Directional · limited data" : `${opportunity.confidence} confidence${assumed ? " · revenue assumed, not measured" : ""}`}</span></div>
    <div className="mt-5"><OpportunityGapChart opportunity={opportunity} /></div>
  </section>;
}
function RevenueMetric({ title, value, label, detail }: { title: string; value: string; label: string; detail: string }) { return <div className="min-w-0 bg-background px-4 py-5 first:pl-0 md:px-6"><p className="font-mono text-[10px] uppercase text-muted-foreground">{title}</p><p className="mt-2 font-mono text-3xl font-semibold text-primary sm:text-4xl">{value}</p><div className="mt-3 flex flex-wrap items-center gap-2"><span className="border border-border px-1.5 py-0.5 font-mono text-[10px] text-foreground">{label}</span><span className="text-xs text-muted-foreground">{detail}</span></div></div>; }
function Diagnosis({ demo, state, assumed, directional, noGap }: { demo: boolean; state?: Variant; assumed: boolean; directional: boolean; noGap: boolean }) {
  const [smallOpen, setSmallOpen] = useState(false);
  const findings = demo && state !== "no-findings" ? REPORT_FINDINGS.filter(f => state !== "no-crawl" || f.source !== "crawl").sort((a,b) => Number(Boolean(b.blocking)) - Number(Boolean(a.blocking)) || Number(Boolean(a.stale || state === "stale")) - Number(Boolean(b.stale || state === "stale"))) : [];
  return <section id="diagnosis"><SectionHeading number="02" title="Diagnosis" note={noGap ? "Measured problems to protect revenue from" : "Measured problems on this page type; these figures do not split the gap"} />
    {!findings.length ? <p className="border-y border-border py-6 text-sm text-muted-foreground">No eligible findings yet. See Limits for what is missing; no diagnosis is inferred.</p> : <div className="divide-y divide-border border-y border-border">{findings.filter(f => !f.small).map(f => <FindingRow key={f.id} finding={f} assumed={assumed} directional={directional} stale={state === "stale"} rulesChanged={state === "rules-changed"} />)}{findings.some(f => f.small) && <div><Button variant="ghost" className="w-full justify-between px-0 text-sm" onClick={() => setSmallOpen(!smallOpen)} aria-expanded={smallOpen}>Smaller findings · {findings.filter(f => f.small).length}<ChevronDown className={`size-4 transition-transform ${smallOpen ? "rotate-180" : ""}`} /></Button>{smallOpen && findings.filter(f => f.small).map(f => <FindingRow key={f.id} finding={f} assumed={assumed} directional={directional} stale={state === "stale"} rulesChanged={state === "rules-changed"} />)}</div>}</div>}
  </section>;
}
function FindingRow({ finding: f, assumed, directional, stale, rulesChanged }: { finding: Finding; assumed: boolean; directional: boolean; stale: boolean; rulesChanged: boolean }) { return <article id={`finding-${f.id}`} className="grid scroll-mt-32 gap-3 py-5 md:grid-cols-[minmax(0,1fr)_minmax(230px,0.6fr)] md:gap-8"><div><div className="flex items-center gap-2 font-mono text-[10px] text-muted-foreground"><span>{f.id.padStart(2,"0")}</span>{f.blocking && <span className="border border-chart-4/40 px-1.5 py-0.5 text-chart-4">BLOCKING</span>}{stale && <Modifier name="Stale · 15 Sep" />}{rulesChanged && f.source !== "crawl" && <Modifier name="Rules changed since this was computed" />}</div><h3 className="mt-2 font-medium">{f.title}</h3><p className="mt-1 text-xs text-muted-foreground">{f.coverage}</p><p className="mt-2 text-xs text-muted-foreground">{f.evidence}</p>{f.overlap && <a href={`#${f.related}`} className="mt-2 inline-block text-xs text-primary underline underline-offset-2">{f.overlap} ↗</a>}</div><div className="flex flex-col items-start justify-center gap-2">{f.figures.map((fig,i) => <Evidence key={i} figure={fig} assumed={assumed} directional={directional} stale={stale} />)}</div></article>; }
function Actions({ demo, state, assumed, directional, opportunity }: { demo: boolean; state?: Variant; assumed: boolean; directional: boolean; opportunity: PageTypeOpportunity }) { const actions = demo ? REPORT_ACTIONS.filter(a => state !== "no-crawl" || (a.issue !== "404" && a.issue !== "Not seen in crawl")) : opportunity.actions.map(a => ({ id: a.id, title: a.title, urls: opportunity.pages.slice(0, a.pagesAffected).map(p => p.url), mechanism: a.why, owner: "SEO", effort: a.effort, confidence: a.confidence, figures: [{ kind: "No estimate" as const, text: "No estimate" }], issue: "Other" }));
  return <section id="actions"><SectionHeading number="03" title="Prioritised actions" note="Fixes ranked by risk and evidence; scenario estimates are never added together" /><div className="divide-y divide-border border-y border-border">{actions.map((a,i) => <article id={`action-${a.id}`} key={a.id} className="grid scroll-mt-32 gap-3 py-5 md:grid-cols-[minmax(0,1fr)_minmax(230px,0.6fr)] md:gap-8"><div className="flex gap-4"><span className="font-mono text-xs text-primary">{String(i+1).padStart(2,"0")}</span><div><h3 className="font-medium">{a.title}</h3><p className="mt-1 text-sm text-muted-foreground">{a.mechanism}</p><a href={`#pages?issue=${encodeURIComponent(a.issue)}`} onClick={(e) => { e.preventDefault(); window.dispatchEvent(new CustomEvent("filter-opportunity-pages", { detail: a.issue })); document.getElementById("pages")?.scrollIntoView({ behavior: "smooth" }); }} className="mt-2 inline-flex items-center gap-1 text-xs text-primary underline underline-offset-2">View {a.urls.length} affected {a.urls.length === 1 ? "URL" : "URLs"}<ArrowRight className="size-3" /></a><p className="mt-3 font-mono text-[11px] text-muted-foreground">{a.owner} · {state === "missing-assessment" || !a.effort ? "Effort not estimated" : `${a.effort} effort`} · {state === "missing-assessment" || !a.confidence ? "Confidence not assessed" : `${a.confidence} confidence`}</p>{"overlap" in a && a.overlap && <a href={`#${a.related}`} className="mt-2 inline-block text-xs text-primary underline underline-offset-2">{a.overlap} ↗</a>}</div></div><div className="flex flex-col items-start justify-center gap-2">{a.figures.map((fig,i) => <Evidence key={i} figure={fig} assumed={assumed} directional={directional} stale={state === "stale"} />)}</div></article>)}</div></section>;
}
function Pages({ demo, state, assumed, directional, opportunity }: { demo: boolean; state?: Variant; assumed: boolean; directional: boolean; opportunity: PageTypeOpportunity }) {
  const [query,setQuery] = useState(""); const [issue,setIssue] = useState("All issues"); const [status,setStatus] = useState("All statuses"); const [sort,setSort] = useState<keyof InvestigatePage>("clicks"); const [ascending,setAscending] = useState(false); const [page,setPage] = useState(1); const [expanded,setExpanded] = useState<string[]>([]);
  useOpportunityFilter(setIssue,setPage);
  const source: InvestigatePage[] = demo ? REPORT_PAGES.map(p => state === "no-crawl" ? { ...p, status: "—", issues: p.issues.filter(i => i !== "404" && i !== "Not seen in crawl") } : state === "not-reached" && p.url.endsWith("paris-lyon") ? { ...p, status: "Not reached" } : p) : opportunity.pages.map(p => ({ url:p.url, clicks:p.clicks, position:p.position, ctr:p.ctr*100, typical:p.expectedCtr*100, revenue:p.revenue, previous:0, latest:0, status:state === "no-crawl" ? "—" : "Crawl status unavailable", issues:[], figures:[] }));
  const issues = [...new Set(source.flatMap(p => p.issues))]; const statuses = [...new Set(source.map(p => p.status))];
  const rows = useMemo(() => source.filter(p => p.url.toLowerCase().includes(query.toLowerCase()) && (issue === "All issues" || p.issues.includes(issue)) && (status === "All statuses" || p.status === status)).sort((a,b) => { const av = a[sort], bv = b[sort]; return (typeof av === "number" && typeof bv === "number" ? av-bv : String(av).localeCompare(String(bv))) * (ascending ? 1 : -1); }), [source, query, issue, status, sort, ascending]);
  const size=10, total=Math.max(1,Math.ceil(rows.length/size)); const visible=rows.slice((Math.min(page,total)-1)*size, Math.min(page,total)*size);
  const updateIssue=(v:string)=>{setIssue(v);setPage(1)};
  const download=()=>{ const csv=["URL,Clicks (28 d),Position,CTR,Typical CTR,Estimated revenue per year,Week of 15 Sep,Week of 8 Sep,Crawl status,Issues",...rows.map(p=>[p.url,p.clicks,p.position,p.ctr,p.typical,p.revenue,p.latest,p.previous,p.status,p.issues.join("; ")].map(v=>`"${String(v).replaceAll('"','""')}"`).join(","))].join("\r\n"); const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})); const a=document.createElement("a");a.href=url;a.download=`${opportunity.slug}-pages.csv`;a.click();URL.revokeObjectURL(url); };
  const head=(label:string,key:keyof InvestigatePage)=> <Button variant="ghost" size="sm" className="h-auto p-0 text-[10px] font-normal uppercase text-muted-foreground" onClick={()=>{setSort(key);setAscending(sort===key?!ascending:false)}} title={`Sort by ${label}`}>{label}{sort===key ? (ascending ? " ↑" : " ↓") : ""}</Button>;
  return <section id="pages" className="scroll-mt-28"><SectionHeading number="04" title="Pages to investigate" note="One row per URL · click a row to see separate issue figures" /><div className="mb-4 flex flex-wrap items-center gap-2"><label className="relative"><Search className="absolute left-2.5 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground" /><input aria-label="Search URLs" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search URLs" className="h-9 w-48 rounded border border-border bg-surface pl-8 pr-2 text-xs outline-none focus:border-primary" /></label><select aria-label="Filter by issue" value={issue} onChange={e=>updateIssue(e.target.value)} className="h-9 max-w-full rounded border border-border bg-surface px-2 text-xs"><option>All issues</option>{issues.map(i=><option key={i}>{i}</option>)}</select><select aria-label="Filter by crawl status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="h-9 max-w-full rounded border border-border bg-surface px-2 text-xs"><option>All statuses</option>{statuses.map(i=><option key={i}>{i}</option>)}</select><Button variant="outline" size="sm" onClick={download} className="ml-auto" title="Export visible results as CSV"><Download className="size-3.5" /> Export CSV</Button></div>
    <div className="overflow-x-auto border-y border-border"><table className="w-full min-w-[960px] text-left text-xs"><thead className="border-b border-border bg-surface font-mono text-[10px] uppercase text-muted-foreground"><tr><th className="px-3 py-3">{head("URL","url")}</th><th className="px-2 py-3">{head("Clicks · 28 d","clicks")}</th><th className="px-2 py-3">{head("Position","position")}</th><th className="px-2 py-3">{head("CTR vs typical","ctr")}</th><th className="px-2 py-3">{head("Est. revenue","revenue")}</th><th className="px-2 py-3">{head("Week change","latest")}</th><th className="px-2 py-3">{head("Crawl status","status")}</th><th className="px-2 py-3">Issues</th></tr></thead><tbody>{visible.map(p=><PageTableRow key={p.url} p={p} expanded={expanded.includes(p.url)} onToggle={()=>setExpanded(prev=>prev.includes(p.url)?prev.filter(x=>x!==p.url):[...prev,p.url])} assumed={assumed} directional={directional} />)}{!visible.length && <tr><td colSpan={8} className="px-3 py-10 text-center text-muted-foreground">No matching URLs.</td></tr>}</tbody></table></div><div className="mt-3 flex items-center justify-between text-xs text-muted-foreground"><span>{rows.length} URLs · page {Math.min(page,total)} of {total}</span><div className="flex gap-1"><Button variant="outline" size="icon" className="size-7" title="Previous page" disabled={page<=1} onClick={()=>setPage(page-1)}><ChevronLeft /></Button><Button variant="outline" size="icon" className="size-7" title="Next page" disabled={page>=total} onClick={()=>setPage(page+1)}><ChevronRight /></Button></div></div></section>;
}
function useOpportunityFilter(setIssue: (value:string)=>void, setPage:(value:number)=>void) { useEffect(()=>{ const listener=(e:Event)=>{setIssue((e as CustomEvent<string>).detail);setPage(1)};window.addEventListener("filter-opportunity-pages",listener);return()=>window.removeEventListener("filter-opportunity-pages",listener)},[setIssue,setPage]); }
function PageTableRow({ p, expanded, onToggle, assumed, directional }: { p: InvestigatePage; expanded:boolean; onToggle:()=>void; assumed:boolean; directional:boolean }) { const change=p.latest-p.previous;return <><tr onClick={onToggle} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onToggle()}}} tabIndex={0} aria-expanded={expanded} title="Show separate figures for each issue" className="cursor-pointer border-b border-border hover:bg-surface/70 focus:bg-surface/70"><td className="px-3 py-4 font-mono text-foreground"><span className="inline-flex items-center gap-1"><ChevronRight className={`size-3 shrink-0 transition-transform ${expanded?"rotate-90":""}`} />{p.url}</span></td><td className="px-2 py-4 font-mono">{p.clicks.toLocaleString()}</td><td className="px-2 py-4 font-mono">{p.position.toFixed(1)}</td><td className="px-2 py-4 font-mono">{p.ctr.toFixed(1)}% vs {p.typical.toFixed(1)}%</td><td className="px-2 py-4"><Evidence figure={{kind:"On affected pages",text:`${Math.round(p.revenue/1000)}k/yr`}} assumed={assumed} directional={directional} /></td><td className="px-2 py-4 font-mono">{p.previous?`${p.latest} vs ${p.previous} (${change>0?"+":""}${change})`:"No comparison"}<span className="block text-[10px] text-muted-foreground">Observed · vs week of 8 Sep</span></td><td className="px-2 py-4">{p.status}</td><td className="px-2 py-4"><div className="flex flex-wrap gap-1">{p.issues.map(i=><span key={i} className="whitespace-nowrap rounded-sm border border-border bg-surface px-1.5 py-0.5 font-mono text-[10px]">{i}</span>)}</div></td></tr>{expanded && <tr className="bg-surface/50"><td colSpan={8} className="px-5 py-4"><p className="mb-3 font-mono text-[10px] uppercase text-muted-foreground">Issue figures · separate estimates, no combined total</p><div className="flex flex-wrap gap-6">{p.figures.length ? p.figures.map(({issue,figure})=><div key={issue} className="min-w-[160px] border-l border-border pl-3"><p className="mb-2 text-xs font-medium">{issue}</p><Evidence figure={figure} assumed={assumed} directional={directional} /></div>) : <p className="text-xs text-muted-foreground">No issue estimate for this URL.</p>}</div></td></tr>}</>; }
function Limits({ opportunity, demo, state, assumed }: { opportunity: PageTypeOpportunity; demo:boolean; state?:Variant; assumed:boolean }) { const gap=gapOf(opportunity); const items=[<span key="gap">The <Evidence figure={{kind:"Estimated",text:`${money(gap).slice(1)}/yr`}} /> gap is a modelled ceiling difference; it isn't split across the findings above.</span>, ...(assumed?["Revenue is assumed from a configured conversion rate, so conversion performance cannot be diagnosed."]:[]), ...(demo?[`Per-URL revenue sums to the illustrative ${money(1_190_000)} vs Current ${money(1_200_000)} (${money(10_000)} basis difference).`, "1 search URL not seen in the latest crawl: a reason to check, not a known cause.", "Latest crawl on 15 Sep reached 38,400 URLs, below its 50,000 URL limit.", "Site-wide context: domain expiry risk applies to the whole site."]: ["Source coverage and per-URL reconciliation are not available for this page type yet."]), ...(state==="stale"?["Search data is older than 14 days or crawl older than 35 days. Re-sync Search Console and run a new audit; dated findings remain visible above."]:[]), ...(state==="no-crawl"?["No completed crawl. Run an audit to check crawl findings and statuses."]:[]), ...(state==="not-reached"?["The crawl reached its 50,000 URL limit. Linked or sitemap-listed URLs beyond that limit are marked Not reached; increase the crawl limit and run another audit."]:[]), ...(state==="rules-changed"?["Page-type rules changed after a page-type signal was computed. Re-run analysis to refresh its coverage."]:[]), ...(state==="no-findings"?["No eligible findings to diagnose yet. Refresh the missing sources before drawing conclusions."]:[])];return <section id="limits"><SectionHeading number="05" title="Limits" note="What the evidence does not tell us yet" /><ul className="grid gap-3 text-sm text-muted-foreground md:grid-cols-2">{items.map((item,i)=><li key={i} className="border-l-2 border-border pl-3">{item}</li>)}</ul>{state==="no-crawl" && <Button asChild variant="outline" className="mt-5"><Link to="/audit-runs">Run an audit <ArrowRight className="size-4" /></Link></Button>}</section>; }
function Loading() { return <div aria-busy="true" className="space-y-8 animate-pulse">{[200,270,250,300,170].map((height,i)=><div key={i} className="border-t border-border py-5"><div className="mb-5 h-5 w-48 bg-surface" /><div className="grid gap-3 sm:grid-cols-3">{[0,1,2].map(n=><div key={n} className="h-20 bg-surface" />)}</div><div className="mt-4 bg-surface" style={{height}} /></div>)}</div>; }
function Empty({name}:{name:string}) { return <div className="border-y border-border py-16"><p className="font-mono text-xs uppercase text-primary">No data yet</p><h2 className="mt-2 text-xl font-semibold">No report for {name}</h2><p className="mt-2 max-w-lg text-sm text-muted-foreground">Connect Search Console and run an audit to start measuring this page type.</p><div className="mt-6 flex flex-wrap gap-3"><Button asChild><Link to="/settings">Connect data sources</Link></Button><Button asChild variant="outline"><Link to="/audit-runs">Run an audit</Link></Button></div></div>; }
