/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteAuthorityRouteImport } from './routes/website-authority'
import { Route as TechnicalHealthRouteImport } from './routes/technical-health'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RequestDemoRouteImport } from './routes/request-demo'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as EarlyAccessRouteImport } from './routes/early-access'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrawlerRouteImport } from './routes/crawler'
import { Route as BrandAuthorityRouteImport } from './routes/brand-authority'
import { Route as AuditRunsRouteImport } from './routes/audit-runs'
import { Route as AccountSettingsRouteImport } from './routes/account-settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebsiteAuthorityIndexRouteImport } from './routes/website-authority.index'
import { Route as TechnicalHealthIndexRouteImport } from './routes/technical-health.index'
import { Route as WebsiteAuthorityInternalEquityRouteImport } from './routes/website-authority.internal-equity'
import { Route as TechnicalHealthCwvRouteImport } from './routes/technical-health.cwv'
import { Route as BrandAuthoritySiteFocusRouteImport } from './routes/brand-authority_.site-focus'
import { Route as BrandAuthorityPageAgeRouteImport } from './routes/brand-authority_.page-age'
import { Route as BrandAuthorityDomainAuthorityRouteImport } from './routes/brand-authority_.domain-authority'
import { Route as BrandAuthorityDomainAgeRouteImport } from './routes/brand-authority_.domain-age'
import { Route as BrandAuthorityBrandLoveRouteImport } from './routes/brand-authority_.brand-love'
import { Route as BrandAuthorityAiVisibilityRouteImport } from './routes/brand-authority_.ai-visibility'
import { Route as AuditRunsRunIdRouteImport } from './routes/audit-runs_.$runId'
import { Route as TechnicalHealthCwvOpportunitiesRouteImport } from './routes/technical-health.cwv.opportunities'
import { Route as TechnicalHealthCwvDeepDiveRouteImport } from './routes/technical-health.cwv.deep-dive'
import { Route as BrandAuthoritySiteFocusTableRouteImport } from './routes/brand-authority_.site-focus_.table'
import { Route as BrandAuthorityPageAgeOutliersRouteImport } from './routes/brand-authority_.page-age.outliers'
import { Route as AuditRunsRunIdUrlsRouteImport } from './routes/audit-runs_.$runId_.urls'
import { Route as AuditRunsRunIdSettingsRouteImport } from './routes/audit-runs_.$runId_.settings'
import { Route as AuditRunsRunIdInventoryRouteImport } from './routes/audit-runs_.$runId_.inventory'
import { Route as AuditRunsRunIdChangesRouteImport } from './routes/audit-runs_.$runId_.changes'
import { Route as AuditRunsRunIdIssuesIssueIdRouteImport } from './routes/audit-runs_.$runId_.issues.$issueId'

const WebsiteAuthorityRoute = WebsiteAuthorityRouteImport.update({
  id: '/website-authority',
  path: '/website-authority',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalHealthRoute = TechnicalHealthRouteImport.update({
  id: '/technical-health',
  path: '/technical-health',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestDemoRoute = RequestDemoRouteImport.update({
  id: '/request-demo',
  path: '/request-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyAccessRoute = EarlyAccessRouteImport.update({
  id: '/early-access',
  path: '/early-access',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrawlerRoute = CrawlerRouteImport.update({
  id: '/crawler',
  path: '/crawler',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandAuthorityRoute = BrandAuthorityRouteImport.update({
  id: '/brand-authority',
  path: '/brand-authority',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRunsRoute = AuditRunsRouteImport.update({
  id: '/audit-runs',
  path: '/audit-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account-settings',
  path: '/account-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteAuthorityIndexRoute = WebsiteAuthorityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebsiteAuthorityRoute,
} as any)
const TechnicalHealthIndexRoute = TechnicalHealthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TechnicalHealthRoute,
} as any)
const WebsiteAuthorityInternalEquityRoute =
  WebsiteAuthorityInternalEquityRouteImport.update({
    id: '/internal-equity',
    path: '/internal-equity',
    getParentRoute: () => WebsiteAuthorityRoute,
  } as any)
const TechnicalHealthCwvRoute = TechnicalHealthCwvRouteImport.update({
  id: '/cwv',
  path: '/cwv',
  getParentRoute: () => TechnicalHealthRoute,
} as any)
const BrandAuthoritySiteFocusRoute = BrandAuthoritySiteFocusRouteImport.update({
  id: '/brand-authority_/site-focus',
  path: '/brand-authority/site-focus',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandAuthorityPageAgeRoute = BrandAuthorityPageAgeRouteImport.update({
  id: '/brand-authority_/page-age',
  path: '/brand-authority/page-age',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandAuthorityDomainAuthorityRoute =
  BrandAuthorityDomainAuthorityRouteImport.update({
    id: '/brand-authority_/domain-authority',
    path: '/brand-authority/domain-authority',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrandAuthorityDomainAgeRoute = BrandAuthorityDomainAgeRouteImport.update({
  id: '/brand-authority_/domain-age',
  path: '/brand-authority/domain-age',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandAuthorityBrandLoveRoute = BrandAuthorityBrandLoveRouteImport.update({
  id: '/brand-authority_/brand-love',
  path: '/brand-authority/brand-love',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandAuthorityAiVisibilityRoute =
  BrandAuthorityAiVisibilityRouteImport.update({
    id: '/brand-authority_/ai-visibility',
    path: '/brand-authority/ai-visibility',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuditRunsRunIdRoute = AuditRunsRunIdRouteImport.update({
  id: '/audit-runs_/$runId',
  path: '/audit-runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalHealthCwvOpportunitiesRoute =
  TechnicalHealthCwvOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => TechnicalHealthCwvRoute,
  } as any)
const TechnicalHealthCwvDeepDiveRoute =
  TechnicalHealthCwvDeepDiveRouteImport.update({
    id: '/deep-dive',
    path: '/deep-dive',
    getParentRoute: () => TechnicalHealthCwvRoute,
  } as any)
const BrandAuthoritySiteFocusTableRoute =
  BrandAuthoritySiteFocusTableRouteImport.update({
    id: '/brand-authority_/site-focus_/table',
    path: '/brand-authority/site-focus/table',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrandAuthorityPageAgeOutliersRoute =
  BrandAuthorityPageAgeOutliersRouteImport.update({
    id: '/outliers',
    path: '/outliers',
    getParentRoute: () => BrandAuthorityPageAgeRoute,
  } as any)
const AuditRunsRunIdUrlsRoute = AuditRunsRunIdUrlsRouteImport.update({
  id: '/audit-runs_/$runId_/urls',
  path: '/audit-runs/$runId/urls',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRunsRunIdSettingsRoute = AuditRunsRunIdSettingsRouteImport.update({
  id: '/audit-runs_/$runId_/settings',
  path: '/audit-runs/$runId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRunsRunIdInventoryRoute = AuditRunsRunIdInventoryRouteImport.update({
  id: '/audit-runs_/$runId_/inventory',
  path: '/audit-runs/$runId/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRunsRunIdChangesRoute = AuditRunsRunIdChangesRouteImport.update({
  id: '/audit-runs_/$runId_/changes',
  path: '/audit-runs/$runId/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRunsRunIdIssuesIssueIdRoute =
  AuditRunsRunIdIssuesIssueIdRouteImport.update({
    id: '/audit-runs_/$runId_/issues/$issueId',
    path: '/audit-runs/$runId/issues/$issueId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/audit-runs': typeof AuditRunsRoute
  '/brand-authority': typeof BrandAuthorityRoute
  '/crawler': typeof CrawlerRoute
  '/dashboard': typeof DashboardRoute
  '/early-access': typeof EarlyAccessRoute
  '/onboarding': typeof OnboardingRoute
  '/request-demo': typeof RequestDemoRoute
  '/settings': typeof SettingsRoute
  '/technical-health': typeof TechnicalHealthRouteWithChildren
  '/website-authority': typeof WebsiteAuthorityRouteWithChildren
  '/audit-runs/$runId': typeof AuditRunsRunIdRoute
  '/brand-authority/ai-visibility': typeof BrandAuthorityAiVisibilityRoute
  '/brand-authority/brand-love': typeof BrandAuthorityBrandLoveRoute
  '/brand-authority/domain-age': typeof BrandAuthorityDomainAgeRoute
  '/brand-authority/domain-authority': typeof BrandAuthorityDomainAuthorityRoute
  '/brand-authority/page-age': typeof BrandAuthorityPageAgeRouteWithChildren
  '/brand-authority/site-focus': typeof BrandAuthoritySiteFocusRoute
  '/technical-health/cwv': typeof TechnicalHealthCwvRouteWithChildren
  '/website-authority/internal-equity': typeof WebsiteAuthorityInternalEquityRoute
  '/technical-health/': typeof TechnicalHealthIndexRoute
  '/website-authority/': typeof WebsiteAuthorityIndexRoute
  '/audit-runs/$runId/changes': typeof AuditRunsRunIdChangesRoute
  '/audit-runs/$runId/inventory': typeof AuditRunsRunIdInventoryRoute
  '/audit-runs/$runId/settings': typeof AuditRunsRunIdSettingsRoute
  '/audit-runs/$runId/urls': typeof AuditRunsRunIdUrlsRoute
  '/brand-authority/page-age/outliers': typeof BrandAuthorityPageAgeOutliersRoute
  '/brand-authority/site-focus/table': typeof BrandAuthoritySiteFocusTableRoute
  '/technical-health/cwv/deep-dive': typeof TechnicalHealthCwvDeepDiveRoute
  '/technical-health/cwv/opportunities': typeof TechnicalHealthCwvOpportunitiesRoute
  '/audit-runs/$runId/issues/$issueId': typeof AuditRunsRunIdIssuesIssueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/audit-runs': typeof AuditRunsRoute
  '/brand-authority': typeof BrandAuthorityRoute
  '/crawler': typeof CrawlerRoute
  '/dashboard': typeof DashboardRoute
  '/early-access': typeof EarlyAccessRoute
  '/onboarding': typeof OnboardingRoute
  '/request-demo': typeof RequestDemoRoute
  '/settings': typeof SettingsRoute
  '/audit-runs/$runId': typeof AuditRunsRunIdRoute
  '/brand-authority/ai-visibility': typeof BrandAuthorityAiVisibilityRoute
  '/brand-authority/brand-love': typeof BrandAuthorityBrandLoveRoute
  '/brand-authority/domain-age': typeof BrandAuthorityDomainAgeRoute
  '/brand-authority/domain-authority': typeof BrandAuthorityDomainAuthorityRoute
  '/brand-authority/page-age': typeof BrandAuthorityPageAgeRouteWithChildren
  '/brand-authority/site-focus': typeof BrandAuthoritySiteFocusRoute
  '/technical-health/cwv': typeof TechnicalHealthCwvRouteWithChildren
  '/website-authority/internal-equity': typeof WebsiteAuthorityInternalEquityRoute
  '/technical-health': typeof TechnicalHealthIndexRoute
  '/website-authority': typeof WebsiteAuthorityIndexRoute
  '/audit-runs/$runId/changes': typeof AuditRunsRunIdChangesRoute
  '/audit-runs/$runId/inventory': typeof AuditRunsRunIdInventoryRoute
  '/audit-runs/$runId/settings': typeof AuditRunsRunIdSettingsRoute
  '/audit-runs/$runId/urls': typeof AuditRunsRunIdUrlsRoute
  '/brand-authority/page-age/outliers': typeof BrandAuthorityPageAgeOutliersRoute
  '/brand-authority/site-focus/table': typeof BrandAuthoritySiteFocusTableRoute
  '/technical-health/cwv/deep-dive': typeof TechnicalHealthCwvDeepDiveRoute
  '/technical-health/cwv/opportunities': typeof TechnicalHealthCwvOpportunitiesRoute
  '/audit-runs/$runId/issues/$issueId': typeof AuditRunsRunIdIssuesIssueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/audit-runs': typeof AuditRunsRoute
  '/brand-authority': typeof BrandAuthorityRoute
  '/crawler': typeof CrawlerRoute
  '/dashboard': typeof DashboardRoute
  '/early-access': typeof EarlyAccessRoute
  '/onboarding': typeof OnboardingRoute
  '/request-demo': typeof RequestDemoRoute
  '/settings': typeof SettingsRoute
  '/technical-health': typeof TechnicalHealthRouteWithChildren
  '/website-authority': typeof WebsiteAuthorityRouteWithChildren
  '/audit-runs_/$runId': typeof AuditRunsRunIdRoute
  '/brand-authority_/ai-visibility': typeof BrandAuthorityAiVisibilityRoute
  '/brand-authority_/brand-love': typeof BrandAuthorityBrandLoveRoute
  '/brand-authority_/domain-age': typeof BrandAuthorityDomainAgeRoute
  '/brand-authority_/domain-authority': typeof BrandAuthorityDomainAuthorityRoute
  '/brand-authority_/page-age': typeof BrandAuthorityPageAgeRouteWithChildren
  '/brand-authority_/site-focus': typeof BrandAuthoritySiteFocusRoute
  '/technical-health/cwv': typeof TechnicalHealthCwvRouteWithChildren
  '/website-authority/internal-equity': typeof WebsiteAuthorityInternalEquityRoute
  '/technical-health/': typeof TechnicalHealthIndexRoute
  '/website-authority/': typeof WebsiteAuthorityIndexRoute
  '/audit-runs_/$runId_/changes': typeof AuditRunsRunIdChangesRoute
  '/audit-runs_/$runId_/inventory': typeof AuditRunsRunIdInventoryRoute
  '/audit-runs_/$runId_/settings': typeof AuditRunsRunIdSettingsRoute
  '/audit-runs_/$runId_/urls': typeof AuditRunsRunIdUrlsRoute
  '/brand-authority_/page-age/outliers': typeof BrandAuthorityPageAgeOutliersRoute
  '/brand-authority_/site-focus_/table': typeof BrandAuthoritySiteFocusTableRoute
  '/technical-health/cwv/deep-dive': typeof TechnicalHealthCwvDeepDiveRoute
  '/technical-health/cwv/opportunities': typeof TechnicalHealthCwvOpportunitiesRoute
  '/audit-runs_/$runId_/issues/$issueId': typeof AuditRunsRunIdIssuesIssueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-settings'
    | '/audit-runs'
    | '/brand-authority'
    | '/crawler'
    | '/dashboard'
    | '/early-access'
    | '/onboarding'
    | '/request-demo'
    | '/settings'
    | '/technical-health'
    | '/website-authority'
    | '/audit-runs/$runId'
    | '/brand-authority/ai-visibility'
    | '/brand-authority/brand-love'
    | '/brand-authority/domain-age'
    | '/brand-authority/domain-authority'
    | '/brand-authority/page-age'
    | '/brand-authority/site-focus'
    | '/technical-health/cwv'
    | '/website-authority/internal-equity'
    | '/technical-health/'
    | '/website-authority/'
    | '/audit-runs/$runId/changes'
    | '/audit-runs/$runId/inventory'
    | '/audit-runs/$runId/settings'
    | '/audit-runs/$runId/urls'
    | '/brand-authority/page-age/outliers'
    | '/brand-authority/site-focus/table'
    | '/technical-health/cwv/deep-dive'
    | '/technical-health/cwv/opportunities'
    | '/audit-runs/$runId/issues/$issueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-settings'
    | '/audit-runs'
    | '/brand-authority'
    | '/crawler'
    | '/dashboard'
    | '/early-access'
    | '/onboarding'
    | '/request-demo'
    | '/settings'
    | '/audit-runs/$runId'
    | '/brand-authority/ai-visibility'
    | '/brand-authority/brand-love'
    | '/brand-authority/domain-age'
    | '/brand-authority/domain-authority'
    | '/brand-authority/page-age'
    | '/brand-authority/site-focus'
    | '/technical-health/cwv'
    | '/website-authority/internal-equity'
    | '/technical-health'
    | '/website-authority'
    | '/audit-runs/$runId/changes'
    | '/audit-runs/$runId/inventory'
    | '/audit-runs/$runId/settings'
    | '/audit-runs/$runId/urls'
    | '/brand-authority/page-age/outliers'
    | '/brand-authority/site-focus/table'
    | '/technical-health/cwv/deep-dive'
    | '/technical-health/cwv/opportunities'
    | '/audit-runs/$runId/issues/$issueId'
  id:
    | '__root__'
    | '/'
    | '/account-settings'
    | '/audit-runs'
    | '/brand-authority'
    | '/crawler'
    | '/dashboard'
    | '/early-access'
    | '/onboarding'
    | '/request-demo'
    | '/settings'
    | '/technical-health'
    | '/website-authority'
    | '/audit-runs_/$runId'
    | '/brand-authority_/ai-visibility'
    | '/brand-authority_/brand-love'
    | '/brand-authority_/domain-age'
    | '/brand-authority_/domain-authority'
    | '/brand-authority_/page-age'
    | '/brand-authority_/site-focus'
    | '/technical-health/cwv'
    | '/website-authority/internal-equity'
    | '/technical-health/'
    | '/website-authority/'
    | '/audit-runs_/$runId_/changes'
    | '/audit-runs_/$runId_/inventory'
    | '/audit-runs_/$runId_/settings'
    | '/audit-runs_/$runId_/urls'
    | '/brand-authority_/page-age/outliers'
    | '/brand-authority_/site-focus_/table'
    | '/technical-health/cwv/deep-dive'
    | '/technical-health/cwv/opportunities'
    | '/audit-runs_/$runId_/issues/$issueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AuditRunsRoute: typeof AuditRunsRoute
  BrandAuthorityRoute: typeof BrandAuthorityRoute
  CrawlerRoute: typeof CrawlerRoute
  DashboardRoute: typeof DashboardRoute
  EarlyAccessRoute: typeof EarlyAccessRoute
  OnboardingRoute: typeof OnboardingRoute
  RequestDemoRoute: typeof RequestDemoRoute
  SettingsRoute: typeof SettingsRoute
  TechnicalHealthRoute: typeof TechnicalHealthRouteWithChildren
  WebsiteAuthorityRoute: typeof WebsiteAuthorityRouteWithChildren
  AuditRunsRunIdRoute: typeof AuditRunsRunIdRoute
  BrandAuthorityAiVisibilityRoute: typeof BrandAuthorityAiVisibilityRoute
  BrandAuthorityBrandLoveRoute: typeof BrandAuthorityBrandLoveRoute
  BrandAuthorityDomainAgeRoute: typeof BrandAuthorityDomainAgeRoute
  BrandAuthorityDomainAuthorityRoute: typeof BrandAuthorityDomainAuthorityRoute
  BrandAuthorityPageAgeRoute: typeof BrandAuthorityPageAgeRouteWithChildren
  BrandAuthoritySiteFocusRoute: typeof BrandAuthoritySiteFocusRoute
  AuditRunsRunIdChangesRoute: typeof AuditRunsRunIdChangesRoute
  AuditRunsRunIdInventoryRoute: typeof AuditRunsRunIdInventoryRoute
  AuditRunsRunIdSettingsRoute: typeof AuditRunsRunIdSettingsRoute
  AuditRunsRunIdUrlsRoute: typeof AuditRunsRunIdUrlsRoute
  BrandAuthoritySiteFocusTableRoute: typeof BrandAuthoritySiteFocusTableRoute
  AuditRunsRunIdIssuesIssueIdRoute: typeof AuditRunsRunIdIssuesIssueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website-authority': {
      id: '/website-authority'
      path: '/website-authority'
      fullPath: '/website-authority'
      preLoaderRoute: typeof WebsiteAuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-health': {
      id: '/technical-health'
      path: '/technical-health'
      fullPath: '/technical-health'
      preLoaderRoute: typeof TechnicalHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-demo': {
      id: '/request-demo'
      path: '/request-demo'
      fullPath: '/request-demo'
      preLoaderRoute: typeof RequestDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access': {
      id: '/early-access'
      path: '/early-access'
      fullPath: '/early-access'
      preLoaderRoute: typeof EarlyAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crawler': {
      id: '/crawler'
      path: '/crawler'
      fullPath: '/crawler'
      preLoaderRoute: typeof CrawlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-authority': {
      id: '/brand-authority'
      path: '/brand-authority'
      fullPath: '/brand-authority'
      preLoaderRoute: typeof BrandAuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-runs': {
      id: '/audit-runs'
      path: '/audit-runs'
      fullPath: '/audit-runs'
      preLoaderRoute: typeof AuditRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-settings': {
      id: '/account-settings'
      path: '/account-settings'
      fullPath: '/account-settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-authority/': {
      id: '/website-authority/'
      path: '/'
      fullPath: '/website-authority/'
      preLoaderRoute: typeof WebsiteAuthorityIndexRouteImport
      parentRoute: typeof WebsiteAuthorityRoute
    }
    '/technical-health/': {
      id: '/technical-health/'
      path: '/'
      fullPath: '/technical-health/'
      preLoaderRoute: typeof TechnicalHealthIndexRouteImport
      parentRoute: typeof TechnicalHealthRoute
    }
    '/website-authority/internal-equity': {
      id: '/website-authority/internal-equity'
      path: '/internal-equity'
      fullPath: '/website-authority/internal-equity'
      preLoaderRoute: typeof WebsiteAuthorityInternalEquityRouteImport
      parentRoute: typeof WebsiteAuthorityRoute
    }
    '/technical-health/cwv': {
      id: '/technical-health/cwv'
      path: '/cwv'
      fullPath: '/technical-health/cwv'
      preLoaderRoute: typeof TechnicalHealthCwvRouteImport
      parentRoute: typeof TechnicalHealthRoute
    }
    '/brand-authority_/site-focus': {
      id: '/brand-authority_/site-focus'
      path: '/brand-authority/site-focus'
      fullPath: '/brand-authority/site-focus'
      preLoaderRoute: typeof BrandAuthoritySiteFocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-authority_/page-age': {
      id: '/brand-authority_/page-age'
      path: '/brand-authority/page-age'
      fullPath: '/brand-authority/page-age'
      preLoaderRoute: typeof BrandAuthorityPageAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-authority_/domain-authority': {
      id: '/brand-authority_/domain-authority'
      path: '/brand-authority/domain-authority'
      fullPath: '/brand-authority/domain-authority'
      preLoaderRoute: typeof BrandAuthorityDomainAuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-authority_/domain-age': {
      id: '/brand-authority_/domain-age'
      path: '/brand-authority/domain-age'
      fullPath: '/brand-authority/domain-age'
      preLoaderRoute: typeof BrandAuthorityDomainAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-authority_/brand-love': {
      id: '/brand-authority_/brand-love'
      path: '/brand-authority/brand-love'
      fullPath: '/brand-authority/brand-love'
      preLoaderRoute: typeof BrandAuthorityBrandLoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-authority_/ai-visibility': {
      id: '/brand-authority_/ai-visibility'
      path: '/brand-authority/ai-visibility'
      fullPath: '/brand-authority/ai-visibility'
      preLoaderRoute: typeof BrandAuthorityAiVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-runs_/$runId': {
      id: '/audit-runs_/$runId'
      path: '/audit-runs/$runId'
      fullPath: '/audit-runs/$runId'
      preLoaderRoute: typeof AuditRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-health/cwv/opportunities': {
      id: '/technical-health/cwv/opportunities'
      path: '/opportunities'
      fullPath: '/technical-health/cwv/opportunities'
      preLoaderRoute: typeof TechnicalHealthCwvOpportunitiesRouteImport
      parentRoute: typeof TechnicalHealthCwvRoute
    }
    '/technical-health/cwv/deep-dive': {
      id: '/technical-health/cwv/deep-dive'
      path: '/deep-dive'
      fullPath: '/technical-health/cwv/deep-dive'
      preLoaderRoute: typeof TechnicalHealthCwvDeepDiveRouteImport
      parentRoute: typeof TechnicalHealthCwvRoute
    }
    '/brand-authority_/site-focus_/table': {
      id: '/brand-authority_/site-focus_/table'
      path: '/brand-authority/site-focus/table'
      fullPath: '/brand-authority/site-focus/table'
      preLoaderRoute: typeof BrandAuthoritySiteFocusTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-authority_/page-age/outliers': {
      id: '/brand-authority_/page-age/outliers'
      path: '/outliers'
      fullPath: '/brand-authority/page-age/outliers'
      preLoaderRoute: typeof BrandAuthorityPageAgeOutliersRouteImport
      parentRoute: typeof BrandAuthorityPageAgeRoute
    }
    '/audit-runs_/$runId_/urls': {
      id: '/audit-runs_/$runId_/urls'
      path: '/audit-runs/$runId/urls'
      fullPath: '/audit-runs/$runId/urls'
      preLoaderRoute: typeof AuditRunsRunIdUrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-runs_/$runId_/settings': {
      id: '/audit-runs_/$runId_/settings'
      path: '/audit-runs/$runId/settings'
      fullPath: '/audit-runs/$runId/settings'
      preLoaderRoute: typeof AuditRunsRunIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-runs_/$runId_/inventory': {
      id: '/audit-runs_/$runId_/inventory'
      path: '/audit-runs/$runId/inventory'
      fullPath: '/audit-runs/$runId/inventory'
      preLoaderRoute: typeof AuditRunsRunIdInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-runs_/$runId_/changes': {
      id: '/audit-runs_/$runId_/changes'
      path: '/audit-runs/$runId/changes'
      fullPath: '/audit-runs/$runId/changes'
      preLoaderRoute: typeof AuditRunsRunIdChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-runs_/$runId_/issues/$issueId': {
      id: '/audit-runs_/$runId_/issues/$issueId'
      path: '/audit-runs/$runId/issues/$issueId'
      fullPath: '/audit-runs/$runId/issues/$issueId'
      preLoaderRoute: typeof AuditRunsRunIdIssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TechnicalHealthCwvRouteChildren {
  TechnicalHealthCwvDeepDiveRoute: typeof TechnicalHealthCwvDeepDiveRoute
  TechnicalHealthCwvOpportunitiesRoute: typeof TechnicalHealthCwvOpportunitiesRoute
}

const TechnicalHealthCwvRouteChildren: TechnicalHealthCwvRouteChildren = {
  TechnicalHealthCwvDeepDiveRoute: TechnicalHealthCwvDeepDiveRoute,
  TechnicalHealthCwvOpportunitiesRoute: TechnicalHealthCwvOpportunitiesRoute,
}

const TechnicalHealthCwvRouteWithChildren =
  TechnicalHealthCwvRoute._addFileChildren(TechnicalHealthCwvRouteChildren)

interface TechnicalHealthRouteChildren {
  TechnicalHealthCwvRoute: typeof TechnicalHealthCwvRouteWithChildren
  TechnicalHealthIndexRoute: typeof TechnicalHealthIndexRoute
}

const TechnicalHealthRouteChildren: TechnicalHealthRouteChildren = {
  TechnicalHealthCwvRoute: TechnicalHealthCwvRouteWithChildren,
  TechnicalHealthIndexRoute: TechnicalHealthIndexRoute,
}

const TechnicalHealthRouteWithChildren = TechnicalHealthRoute._addFileChildren(
  TechnicalHealthRouteChildren,
)

interface WebsiteAuthorityRouteChildren {
  WebsiteAuthorityInternalEquityRoute: typeof WebsiteAuthorityInternalEquityRoute
  WebsiteAuthorityIndexRoute: typeof WebsiteAuthorityIndexRoute
}

const WebsiteAuthorityRouteChildren: WebsiteAuthorityRouteChildren = {
  WebsiteAuthorityInternalEquityRoute: WebsiteAuthorityInternalEquityRoute,
  WebsiteAuthorityIndexRoute: WebsiteAuthorityIndexRoute,
}

const WebsiteAuthorityRouteWithChildren =
  WebsiteAuthorityRoute._addFileChildren(WebsiteAuthorityRouteChildren)

interface BrandAuthorityPageAgeRouteChildren {
  BrandAuthorityPageAgeOutliersRoute: typeof BrandAuthorityPageAgeOutliersRoute
}

const BrandAuthorityPageAgeRouteChildren: BrandAuthorityPageAgeRouteChildren = {
  BrandAuthorityPageAgeOutliersRoute: BrandAuthorityPageAgeOutliersRoute,
}

const BrandAuthorityPageAgeRouteWithChildren =
  BrandAuthorityPageAgeRoute._addFileChildren(
    BrandAuthorityPageAgeRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AuditRunsRoute: AuditRunsRoute,
  BrandAuthorityRoute: BrandAuthorityRoute,
  CrawlerRoute: CrawlerRoute,
  DashboardRoute: DashboardRoute,
  EarlyAccessRoute: EarlyAccessRoute,
  OnboardingRoute: OnboardingRoute,
  RequestDemoRoute: RequestDemoRoute,
  SettingsRoute: SettingsRoute,
  TechnicalHealthRoute: TechnicalHealthRouteWithChildren,
  WebsiteAuthorityRoute: WebsiteAuthorityRouteWithChildren,
  AuditRunsRunIdRoute: AuditRunsRunIdRoute,
  BrandAuthorityAiVisibilityRoute: BrandAuthorityAiVisibilityRoute,
  BrandAuthorityBrandLoveRoute: BrandAuthorityBrandLoveRoute,
  BrandAuthorityDomainAgeRoute: BrandAuthorityDomainAgeRoute,
  BrandAuthorityDomainAuthorityRoute: BrandAuthorityDomainAuthorityRoute,
  BrandAuthorityPageAgeRoute: BrandAuthorityPageAgeRouteWithChildren,
  BrandAuthoritySiteFocusRoute: BrandAuthoritySiteFocusRoute,
  AuditRunsRunIdChangesRoute: AuditRunsRunIdChangesRoute,
  AuditRunsRunIdInventoryRoute: AuditRunsRunIdInventoryRoute,
  AuditRunsRunIdSettingsRoute: AuditRunsRunIdSettingsRoute,
  AuditRunsRunIdUrlsRoute: AuditRunsRunIdUrlsRoute,
  BrandAuthoritySiteFocusTableRoute: BrandAuthoritySiteFocusTableRoute,
  AuditRunsRunIdIssuesIssueIdRoute: AuditRunsRunIdIssuesIssueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
