/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnicalHealthRouteImport } from './routes/technical-health'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrandAuthorityRouteImport } from './routes/brand-authority'
import { Route as AuditRunsRouteImport } from './routes/audit-runs'
import { Route as AccountSettingsRouteImport } from './routes/account-settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechnicalHealthIndexRouteImport } from './routes/technical-health.index'
import { Route as TechnicalHealthCwvRouteImport } from './routes/technical-health.cwv'
import { Route as BrandAuthoritySiteFocusRouteImport } from './routes/brand-authority_.site-focus'
import { Route as BrandAuthorityPageAgeRouteImport } from './routes/brand-authority_.page-age'
import { Route as BrandAuthorityDomainAgeRouteImport } from './routes/brand-authority_.domain-age'
import { Route as AuditRunsRunIdRouteImport } from './routes/audit-runs_.$runId'
import { Route as TechnicalHealthCwvOpportunitiesRouteImport } from './routes/technical-health.cwv.opportunities'
import { Route as TechnicalHealthCwvDeepDiveRouteImport } from './routes/technical-health.cwv.deep-dive'
import { Route as BrandAuthorityPageAgeOutliersRouteImport } from './routes/brand-authority_.page-age.outliers'
import { Route as AuditRunsRunIdSettingsRouteImport } from './routes/audit-runs_.$runId_.settings'
import { Route as AuditRunsRunIdUrlsRouteImport } from './routes/audit-runs_.$runId_.urls'
import { Route as AuditRunsRunIdIssuesIssueIdRouteImport } from './routes/audit-runs_.$runId_.issues.$issueId'

const TechnicalHealthRoute = TechnicalHealthRouteImport.update({
  id: '/technical-health',
  path: '/technical-health',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandAuthorityRoute = BrandAuthorityRouteImport.update({
  id: '/brand-authority',
  path: '/brand-authority',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRunsRoute = AuditRunsRouteImport.update({
  id: '/audit-runs',
  path: '/audit-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account-settings',
  path: '/account-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalHealthIndexRoute = TechnicalHealthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TechnicalHealthRoute,
} as any)
const TechnicalHealthCwvRoute = TechnicalHealthCwvRouteImport.update({
  id: '/cwv',
  path: '/cwv',
  getParentRoute: () => TechnicalHealthRoute,
} as any)
const BrandAuthoritySiteFocusRoute = BrandAuthoritySiteFocusRouteImport.update({
  id: '/brand-authority_/site-focus',
  path: '/brand-authority/site-focus',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandAuthorityPageAgeRoute = BrandAuthorityPageAgeRouteImport.update({
  id: '/brand-authority_/page-age',
  path: '/brand-authority/page-age',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandAuthorityDomainAgeRoute = BrandAuthorityDomainAgeRouteImport.update({
  id: '/brand-authority_/domain-age',
  path: '/brand-authority/domain-age',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRunsRunIdRoute = AuditRunsRunIdRouteImport.update({
  id: '/audit-runs_/$runId',
  path: '/audit-runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalHealthCwvOpportunitiesRoute =
  TechnicalHealthCwvOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => TechnicalHealthCwvRoute,
  } as any)
const TechnicalHealthCwvDeepDiveRoute =
  TechnicalHealthCwvDeepDiveRouteImport.update({
    id: '/deep-dive',
    path: '/deep-dive',
    getParentRoute: () => TechnicalHealthCwvRoute,
  } as any)
const BrandAuthorityPageAgeOutliersRoute =
  BrandAuthorityPageAgeOutliersRouteImport.update({
    id: '/outliers',
    path: '/outliers',
    getParentRoute: () => BrandAuthorityPageAgeRoute,
  } as any)
const AuditRunsRunIdSettingsRoute = AuditRunsRunIdSettingsRouteImport.update({
  id: '/audit-runs_/$runId_/settings',
  path: '/audit-runs/$runId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRunsRunIdUrlsRoute = AuditRunsRunIdUrlsRouteImport.update({
  id: '/audit-runs_/$runId_/urls',
  path: '/audit-runs/$runId/urls',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRunsRunIdIssuesIssueIdRoute =
  AuditRunsRunIdIssuesIssueIdRouteImport.update({
    id: '/audit-runs_/$runId_/issues/$issueId',
    path: '/audit-runs/$runId/issues/$issueId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/audit-runs': typeof AuditRunsRoute
  '/brand-authority': typeof BrandAuthorityRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/technical-health': typeof TechnicalHealthRouteWithChildren
  '/audit-runs/$runId': typeof AuditRunsRunIdRoute
  '/brand-authority/domain-age': typeof BrandAuthorityDomainAgeRoute
  '/brand-authority/page-age': typeof BrandAuthorityPageAgeRouteWithChildren
  '/brand-authority/site-focus': typeof BrandAuthoritySiteFocusRoute
  '/technical-health/cwv': typeof TechnicalHealthCwvRouteWithChildren
  '/technical-health/': typeof TechnicalHealthIndexRoute
  '/audit-runs/$runId/settings': typeof AuditRunsRunIdSettingsRoute
  '/brand-authority/page-age/outliers': typeof BrandAuthorityPageAgeOutliersRoute
  '/technical-health/cwv/deep-dive': typeof TechnicalHealthCwvDeepDiveRoute
  '/technical-health/cwv/opportunities': typeof TechnicalHealthCwvOpportunitiesRoute
  '/audit-runs/$runId/issues/$issueId': typeof AuditRunsRunIdIssuesIssueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/audit-runs': typeof AuditRunsRoute
  '/brand-authority': typeof BrandAuthorityRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/audit-runs/$runId': typeof AuditRunsRunIdRoute
  '/brand-authority/domain-age': typeof BrandAuthorityDomainAgeRoute
  '/brand-authority/page-age': typeof BrandAuthorityPageAgeRouteWithChildren
  '/brand-authority/site-focus': typeof BrandAuthoritySiteFocusRoute
  '/technical-health/cwv': typeof TechnicalHealthCwvRouteWithChildren
  '/technical-health': typeof TechnicalHealthIndexRoute
  '/audit-runs/$runId/settings': typeof AuditRunsRunIdSettingsRoute
  '/brand-authority/page-age/outliers': typeof BrandAuthorityPageAgeOutliersRoute
  '/technical-health/cwv/deep-dive': typeof TechnicalHealthCwvDeepDiveRoute
  '/technical-health/cwv/opportunities': typeof TechnicalHealthCwvOpportunitiesRoute
  '/audit-runs/$runId/issues/$issueId': typeof AuditRunsRunIdIssuesIssueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/audit-runs': typeof AuditRunsRoute
  '/brand-authority': typeof BrandAuthorityRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/technical-health': typeof TechnicalHealthRouteWithChildren
  '/audit-runs_/$runId': typeof AuditRunsRunIdRoute
  '/brand-authority_/domain-age': typeof BrandAuthorityDomainAgeRoute
  '/brand-authority_/page-age': typeof BrandAuthorityPageAgeRouteWithChildren
  '/brand-authority_/site-focus': typeof BrandAuthoritySiteFocusRoute
  '/technical-health/cwv': typeof TechnicalHealthCwvRouteWithChildren
  '/technical-health/': typeof TechnicalHealthIndexRoute
  '/audit-runs_/$runId_/settings': typeof AuditRunsRunIdSettingsRoute
  '/brand-authority_/page-age/outliers': typeof BrandAuthorityPageAgeOutliersRoute
  '/technical-health/cwv/deep-dive': typeof TechnicalHealthCwvDeepDiveRoute
  '/technical-health/cwv/opportunities': typeof TechnicalHealthCwvOpportunitiesRoute
  '/audit-runs_/$runId_/issues/$issueId': typeof AuditRunsRunIdIssuesIssueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-settings'
    | '/audit-runs'
    | '/brand-authority'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/technical-health'
    | '/audit-runs/$runId'
    | '/brand-authority/domain-age'
    | '/brand-authority/page-age'
    | '/brand-authority/site-focus'
    | '/technical-health/cwv'
    | '/technical-health/'
    | '/audit-runs/$runId/settings'
    | '/brand-authority/page-age/outliers'
    | '/technical-health/cwv/deep-dive'
    | '/technical-health/cwv/opportunities'
    | '/audit-runs/$runId/issues/$issueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-settings'
    | '/audit-runs'
    | '/brand-authority'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/audit-runs/$runId'
    | '/brand-authority/domain-age'
    | '/brand-authority/page-age'
    | '/brand-authority/site-focus'
    | '/technical-health/cwv'
    | '/technical-health'
    | '/audit-runs/$runId/settings'
    | '/brand-authority/page-age/outliers'
    | '/technical-health/cwv/deep-dive'
    | '/technical-health/cwv/opportunities'
    | '/audit-runs/$runId/issues/$issueId'
  id:
    | '__root__'
    | '/'
    | '/account-settings'
    | '/audit-runs'
    | '/brand-authority'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/technical-health'
    | '/audit-runs_/$runId'
    | '/brand-authority_/domain-age'
    | '/brand-authority_/page-age'
    | '/brand-authority_/site-focus'
    | '/technical-health/cwv'
    | '/technical-health/'
    | '/audit-runs_/$runId_/settings'
    | '/brand-authority_/page-age/outliers'
    | '/technical-health/cwv/deep-dive'
    | '/technical-health/cwv/opportunities'
    | '/audit-runs_/$runId_/issues/$issueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AuditRunsRoute: typeof AuditRunsRoute
  BrandAuthorityRoute: typeof BrandAuthorityRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  TechnicalHealthRoute: typeof TechnicalHealthRouteWithChildren
  AuditRunsRunIdRoute: typeof AuditRunsRunIdRoute
  BrandAuthorityDomainAgeRoute: typeof BrandAuthorityDomainAgeRoute
  BrandAuthorityPageAgeRoute: typeof BrandAuthorityPageAgeRouteWithChildren
  BrandAuthoritySiteFocusRoute: typeof BrandAuthoritySiteFocusRoute
  AuditRunsRunIdSettingsRoute: typeof AuditRunsRunIdSettingsRoute
  AuditRunsRunIdIssuesIssueIdRoute: typeof AuditRunsRunIdIssuesIssueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technical-health': {
      id: '/technical-health'
      path: '/technical-health'
      fullPath: '/technical-health'
      preLoaderRoute: typeof TechnicalHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-authority': {
      id: '/brand-authority'
      path: '/brand-authority'
      fullPath: '/brand-authority'
      preLoaderRoute: typeof BrandAuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-runs': {
      id: '/audit-runs'
      path: '/audit-runs'
      fullPath: '/audit-runs'
      preLoaderRoute: typeof AuditRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-settings': {
      id: '/account-settings'
      path: '/account-settings'
      fullPath: '/account-settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-health/': {
      id: '/technical-health/'
      path: '/'
      fullPath: '/technical-health/'
      preLoaderRoute: typeof TechnicalHealthIndexRouteImport
      parentRoute: typeof TechnicalHealthRoute
    }
    '/technical-health/cwv': {
      id: '/technical-health/cwv'
      path: '/cwv'
      fullPath: '/technical-health/cwv'
      preLoaderRoute: typeof TechnicalHealthCwvRouteImport
      parentRoute: typeof TechnicalHealthRoute
    }
    '/brand-authority_/site-focus': {
      id: '/brand-authority_/site-focus'
      path: '/brand-authority/site-focus'
      fullPath: '/brand-authority/site-focus'
      preLoaderRoute: typeof BrandAuthoritySiteFocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-authority_/page-age': {
      id: '/brand-authority_/page-age'
      path: '/brand-authority/page-age'
      fullPath: '/brand-authority/page-age'
      preLoaderRoute: typeof BrandAuthorityPageAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-authority_/domain-age': {
      id: '/brand-authority_/domain-age'
      path: '/brand-authority/domain-age'
      fullPath: '/brand-authority/domain-age'
      preLoaderRoute: typeof BrandAuthorityDomainAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-runs_/$runId': {
      id: '/audit-runs_/$runId'
      path: '/audit-runs/$runId'
      fullPath: '/audit-runs/$runId'
      preLoaderRoute: typeof AuditRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-health/cwv/opportunities': {
      id: '/technical-health/cwv/opportunities'
      path: '/opportunities'
      fullPath: '/technical-health/cwv/opportunities'
      preLoaderRoute: typeof TechnicalHealthCwvOpportunitiesRouteImport
      parentRoute: typeof TechnicalHealthCwvRoute
    }
    '/technical-health/cwv/deep-dive': {
      id: '/technical-health/cwv/deep-dive'
      path: '/deep-dive'
      fullPath: '/technical-health/cwv/deep-dive'
      preLoaderRoute: typeof TechnicalHealthCwvDeepDiveRouteImport
      parentRoute: typeof TechnicalHealthCwvRoute
    }
    '/brand-authority_/page-age/outliers': {
      id: '/brand-authority_/page-age/outliers'
      path: '/outliers'
      fullPath: '/brand-authority/page-age/outliers'
      preLoaderRoute: typeof BrandAuthorityPageAgeOutliersRouteImport
      parentRoute: typeof BrandAuthorityPageAgeRoute
    }
    '/audit-runs_/$runId_/settings': {
      id: '/audit-runs_/$runId_/settings'
      path: '/audit-runs/$runId/settings'
      fullPath: '/audit-runs/$runId/settings'
      preLoaderRoute: typeof AuditRunsRunIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-runs_/$runId_/issues/$issueId': {
      id: '/audit-runs_/$runId_/issues/$issueId'
      path: '/audit-runs/$runId/issues/$issueId'
      fullPath: '/audit-runs/$runId/issues/$issueId'
      preLoaderRoute: typeof AuditRunsRunIdIssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TechnicalHealthCwvRouteChildren {
  TechnicalHealthCwvDeepDiveRoute: typeof TechnicalHealthCwvDeepDiveRoute
  TechnicalHealthCwvOpportunitiesRoute: typeof TechnicalHealthCwvOpportunitiesRoute
}

const TechnicalHealthCwvRouteChildren: TechnicalHealthCwvRouteChildren = {
  TechnicalHealthCwvDeepDiveRoute: TechnicalHealthCwvDeepDiveRoute,
  TechnicalHealthCwvOpportunitiesRoute: TechnicalHealthCwvOpportunitiesRoute,
}

const TechnicalHealthCwvRouteWithChildren =
  TechnicalHealthCwvRoute._addFileChildren(TechnicalHealthCwvRouteChildren)

interface TechnicalHealthRouteChildren {
  TechnicalHealthCwvRoute: typeof TechnicalHealthCwvRouteWithChildren
  TechnicalHealthIndexRoute: typeof TechnicalHealthIndexRoute
}

const TechnicalHealthRouteChildren: TechnicalHealthRouteChildren = {
  TechnicalHealthCwvRoute: TechnicalHealthCwvRouteWithChildren,
  TechnicalHealthIndexRoute: TechnicalHealthIndexRoute,
}

const TechnicalHealthRouteWithChildren = TechnicalHealthRoute._addFileChildren(
  TechnicalHealthRouteChildren,
)

interface BrandAuthorityPageAgeRouteChildren {
  BrandAuthorityPageAgeOutliersRoute: typeof BrandAuthorityPageAgeOutliersRoute
}

const BrandAuthorityPageAgeRouteChildren: BrandAuthorityPageAgeRouteChildren = {
  BrandAuthorityPageAgeOutliersRoute: BrandAuthorityPageAgeOutliersRoute,
}

const BrandAuthorityPageAgeRouteWithChildren =
  BrandAuthorityPageAgeRoute._addFileChildren(
    BrandAuthorityPageAgeRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AuditRunsRoute: AuditRunsRoute,
  BrandAuthorityRoute: BrandAuthorityRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  TechnicalHealthRoute: TechnicalHealthRouteWithChildren,
  AuditRunsRunIdRoute: AuditRunsRunIdRoute,
  BrandAuthorityDomainAgeRoute: BrandAuthorityDomainAgeRoute,
  BrandAuthorityPageAgeRoute: BrandAuthorityPageAgeRouteWithChildren,
  BrandAuthoritySiteFocusRoute: BrandAuthoritySiteFocusRoute,
  AuditRunsRunIdSettingsRoute: AuditRunsRunIdSettingsRoute,
  AuditRunsRunIdIssuesIssueIdRoute: AuditRunsRunIdIssuesIssueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
